version: "3.9"

volumes:
  db_data:
    driver: local

services:
  db:
    image: postgres:14
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: zigwheelo
      POSTGRES_USER: zigwheelo
      POSTGRES_PASSWORD: 12345
    ports:
      - "9532:5432"