[versions]
ktor = "2.0.0-beta-1"
logback = "1.2.6"
kotlin = "1.6.10"
kotlinx-serialization = "1.3.2"
kmongo = "4.4.0"
arrow = "1.0.1"
compose-version = "1.2.0-alpha03"
compose-compiler-version = "1.2.0-alpha03"
core-ktx = "1.7.0"
material = "1.5.0"
lifecycle = "2.3.1"
activityCompose = "1.3.1"
coroutines = "1.5.2-native-mt"
play-services-maps = "18.0.2"
maps-ktx = "3.3.0"
maps-compose = "1.3.0"
napier = "2.4.0"

[libraries]
kotlinx-serialization-core = { module = "org.jetbrains.kotlinx:kotlinx-serialization-core", version.ref = "kotlinx-serialization" }
ktorServerCallLogging = { module = "io.ktor:ktor-server-call-logging", version.ref = "ktor" }
ktorServerContentNegociation = { module = "io.ktor:ktor-server-content-negotiation", version.ref = "ktor" }
ktorServerCors = { module = "io.ktor:ktor-server-cors", version.ref = "ktor" }
ktorServerCore = { module = "io.ktor:ktor-server-core", version.ref = "ktor" }
ktorServerSerializationJson = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktorServerCio = { module = "io.ktor:ktor-server-cio", version.ref = "ktor" }

ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }

kotlinCoroutinesAndroid = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
ktor-client-json = { module = "io.ktor:ktor-client-json", version.ref = "ktor" }
ktorClientCio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }
ktorClientJs = { module = "io.ktor:ktor-client-js", version.ref = "ktor" }
ktorClientAndroid = { module = "io.ktor:ktor-client-android", version.ref = "ktor" }
ktorClientIOS = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
ktor-client-logging = { module = "io.ktor:ktor-client-logging", version.ref = "ktor" }
napier = { module = "io.github.aakira:napier", version.ref = "napier" }

kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }

logback = { module = "ch.qos.logback:logback-classic", version.ref = "logback" }

ktorServerTests = { module = "io.ktor:ktor-server-tests", version.ref = "ktor" }
kotlinTest = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "kotlin" }

kmongo = { module = "org.litote.kmongo:kmongo-serialization", version.ref = "kmongo" }
kmongoCoroutine = { module = "org.litote.kmongo:kmongo-coroutine-serialization", version.ref = "kmongo" }

arrow = { module = "io.arrow-kt:arrow-core", version.ref = "arrow" }

android-core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
android-compose-compiler = { module = "androidx.compose.compiler:compiler", version.ref = "compose-compiler-version" }
android-compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose-version" }
android-compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose-version" }
android-compose-material = { module = "androidx.compose.material:material", version.ref = "compose-version" }
android-compose-ui-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose-version" }
android-lifecycle = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
android-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "activityCompose" }
android-google-maps = { module = "com.google.android.gms:play-services-maps", version.ref = "play-services-maps" }
android-google-maps-compose = { module = "com.google.maps.android:maps-compose", version.ref = "maps-compose" }
android-maps-ktx = { module = "com.google.maps.android:maps-ktx", version.ref = "maps-ktx" }

[bundles]
serverDependencies = [
    "kotlinx-serialization-core",
    "ktorServerCallLogging",
    "ktorServerCors",
    "ktorServerContentNegociation",
    "ktorServerCore",
    "ktorServerSerializationJson",
    "ktorServerCio",
    "logback",
    "arrow",
]
testDependencies = ["ktorServerTests", "kotlinTest"]

crawlerDependencies = [
    "ktor-client-core",
    "ktorClientCio",
    "ktor-client-json",
    "ktor-serialization-kotlinx-json",
    "ktor-client-content-negotiation",
    "kotlinx-serialization-json",
    "arrow",
]
databaseDependencies = [
    "kmongo",
    "kmongoCoroutine",
    "kotlinx-serialization-json",
    "arrow",
]

apiDependencies = [
    "ktor-client-core",
    "kotlinx-coroutines-core",
    "ktor-client-json",
    "ktor-serialization-kotlinx-json",
    "ktor-client-content-negotiation",
    "kotlinx-serialization-core",
    "napier",
    "ktor-client-logging",
]

apiJvmDependencies = [
    "ktorClientCio",
]

apiJsDependencies = [
    "ktorClientJs",
]

apiAndroidDependencies = [
    "ktorClientAndroid",
    "kotlinCoroutinesAndroid",
]

apiIOSDependencies = [
    "ktorClientIOS",
]

androidDependencies = [
    "android-core-ktx",
    "android-compose-compiler",
    "android-compose-foundation",
    "android-compose-ui",
    "android-compose-material",
    "android-compose-ui-preview",
    "android-google-maps",
    "android-maps-ktx",
    "android-lifecycle",
    "android-activity-compose",
    "android-google-maps-compose",
    "arrow",
]