[versions]
ktor = "2.0.0-beta-1"
logback = "1.2.6"
kotlin = "1.6.10"
kotlinx-serialization = "1.3.1"

[libraries]
ktorServerCallLogging = { module="io.ktor:ktor-server-call-logging", version.ref="ktor" }
ktorServerContentNegociation = { module="io.ktor:ktor-server-content-negotiation", version.ref="ktor" }
ktorServerCore = { module="io.ktor:ktor-server-core", version.ref="ktor" }
ktorServerSerializationJson = { module="io.ktor:ktor-serialization-jackson", version.ref="ktor" }
ktorServerCio = { module="io.ktor:ktor-server-cio", version.ref="ktor" }

ktorClient = { module="io.ktor:ktor-client-core", version.ref="ktor" }
ktorClientCio = { module="io.ktor:ktor-client-cio", version.ref="ktor" }
ktorClientJson = { module="io.ktor:ktor-serialization-kotlinx-json", version.ref="ktor" }
ktorClientContentNegociation = { module="io.ktor:ktor-client-content-negotiation", version.ref="ktor" }
kotlinx-serialization = { module="org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref="kotlinx-serialization" }

logback = { module="ch.qos.logback:logback-classic", version.ref="logback" }

ktorServerTests = { module="io.ktor:ktor-server-tests", version.ref="ktor" }
kotlinTest = { module="org.jetbrains.kotlin:kotlin-test-junit", version.ref="kotlin" }

[bundles]
serverDependencies = [
  "ktorServerCallLogging",
  "ktorServerContentNegociation",
  "ktorServerCore",
  "ktorServerSerializationJson",
  "ktorServerCio",
  "logback",
]
testDependencies = ["ktorServerTests", "kotlinTest"]
crawlerDependencies = [
  "ktorClient",
  "ktorClientCio",
  "ktorClientJson",
  "ktorClientContentNegociation",
  "kotlinx-serialization"
]